<?php
namespace backend\components;
use common\components\aliyunsms\Sms;
use Yii;
use yii\base\Component;
use common\models\system\Setting;

/**
 * Created by PhpStorm.
 * User: zpc
 * Date: 2017/9/9
 * Time: 17:30
 */
class AdminTool extends Component
{
    private $_models;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $models = Setting::find()->where(['is_visible'=>Setting::SETTING_ACTIVE])->all();

        $newModels = [];
        foreach ($models as $model) {
            $newModels[$model->key] = $model;
        }

        $this->_models = $newModels;
    }
    //给对应用户发送短信
    public function sms_phone($key, $temp, $params)
    {
        $result = [];
        $sms_phone = $this->getSmsPhone($key);
        if (is_array($sms_phone)) {
            foreach ($sms_phone as $phone) {
                $result[] = Yii::$app->sms->sendSms('豹品淘', $temp, $phone, $params);
            }
        } else {
            $result[] = Yii::$app->sms->sendSms('豹品淘', $temp, $sms_phone, $params);
        }
        //判断是否有发送失败情况
        foreach ($result as $re) {
            if ($re->Code != 'OK') {
                //发送失败
            }
        }
        return $result;
    }

    //获取通知手机号，并且分割
    public function getSmsPhone($key)
    {
        $phone_list = $this->getValue($key);
        if (empty($phone_list) || !isset($phone_list)) { //如果为空则不发送
            return false;
        }
        //判断是否有逗号
        if (strpos($phone_list, ',')) {
            return explode(',', $phone_list);
        }
        return $phone_list;
    }

    //获取其中一key
    public function getValue($key)
    {
        return $this->_models[$key]->value;
    }
}